name = "chitalk"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# next-on-pages output directory
pages_build_output_dir = ".vercel/output/static"

[vars]
# Environment variables can be set here or in Cloudflare dashboard
